# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 1.6.2"

Vagrant.configure("2") do |config|
    config.vm.define "vagrant-windows-7"
    config.vm.box = "windows_7"
    config.vm.communicator = "winrm"

    config.winrm.username = "vagrant"
    config.winrm.password = "vagrant"

    config.vm.guest = :windows
    config.windows.halt_timeout = 15

    config.vm.network :forwarded_port, guest: 3389, host: 3389, id: "rdp", auto_correct: true

    config.vm.provision "shell", path: "../scripts/puppet.bat"
    config.vm.provision "shell", path: "../scripts/chocolatey.bat"
    config.vm.provision "shell", path: "../scripts/chocopacks.bat"

    config.vm.provider :virtualbox do |v, override|
        v.gui = true
        v.customize ["setextradata", "global", "GUI/SuppressMessages", "all" ]
    end
end
